{
  "cveId": "CVE-2025-46150",
  "eventName": "Initial Analysis",
  "cveChangeId": "4D1B26ED-D8C9-47BF-A8E9-7A21B5F0DB69",
  "sourceIdentifier": "nvd@nist.gov",
  "created": "2025-10-03T17:58:05.150",
  "details": [
    {
      "action": "Added",
      "type": "CWE",
      "newValue": "NVD-CWE-noinfo"
    },
    {
      "action": "Added",
      "type": "CPE Configuration",
      "newValue": "\nOR\n          *cpe:2.3:a:linuxfoundation:pytorch:*:*:*:*:*:python:*:* versions from (including) 2.6.0 up to (excluding) 2.7.0"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "MITRE: https://gist.github.com/shaoyuyoung/4bcefba4004f8271e64b5185c95a248a Types: Third Party Advisory"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "MITRE: https://github.com/pytorch/pytorch/issues/141538 Types: Issue Tracking"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "MITRE: https://github.com/pytorch/pytorch/issues/141538#issuecomment-2537424658 Types: Issue Tracking"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "MITRE: https://github.com/pytorch/pytorch/pull/144395 Types: Issue Tracking, Patch"
    }
  ]
}