{
  "cveId": "CVE-2025-46149",
  "eventName": "Initial Analysis",
  "cveChangeId": "05647143-C3EB-4893-B343-B7F92801CFD8",
  "sourceIdentifier": "nvd@nist.gov",
  "created": "2025-10-03T17:58:39.477",
  "details": [
    {
      "action": "Added",
      "type": "CPE Configuration",
      "newValue": "\nOR\n          *cpe:2.3:a:linuxfoundation:pytorch:*:*:*:*:*:python:*:* versions from (including) 2.6.0 up to (excluding) 2.7.0"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "MITRE: https://gist.github.com/shaoyuyoung/4bcefba4004f8271e64b5185c95a248a Types: Third Party Advisory"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "MITRE: https://github.com/pytorch/pytorch/issues/147848 Types: Issue Tracking"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "MITRE: https://github.com/pytorch/pytorch/pull/147961 Types: Issue Tracking, Patch"
    }
  ]
}