{
  "cveId": "CVE-2025-46148",
  "eventName": "Initial Analysis",
  "cveChangeId": "5719674A-8E14-4A47-A060-84F75BED8C7C",
  "sourceIdentifier": "nvd@nist.gov",
  "created": "2025-10-03T17:59:26.460",
  "details": [
    {
      "action": "Added",
      "type": "CWE",
      "newValue": "NVD-CWE-noinfo"
    },
    {
      "action": "Added",
      "type": "CPE Configuration",
      "newValue": "\nOR\n          *cpe:2.3:a:linuxfoundation:pytorch:*:*:*:*:*:python:*:* versions up to (including) 2.6.0"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "MITRE: https://gist.github.com/shaoyuyoung/4bcefba4004f8271e64b5185c95a248a Types: Third Party Advisory"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "MITRE: https://gist.github.com/shaoyuyoung/65a587a579dfdff887b9b35bb79b9093 Types: Third Party Advisory"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "MITRE: https://github.com/pytorch/pytorch/issues/151198 Types: Issue Tracking"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "MITRE: https://github.com/pytorch/pytorch/pull/152993 Types: Issue Tracking, Patch"
    }
  ]
}