{
  "cveId": "CVE-2020-36813",
  "eventName": "New CVE Received",
  "cveChangeId": "B984006E-1172-4390-8530-0EB0FDA8BBA6",
  "sourceIdentifier": "416baaa9-dc9f-4396-8d5f-8c081fb06d67",
  "created": "2025-09-16T16:15:38.423",
  "details": [
    {
      "action": "Added",
      "type": "Description",
      "newValue": "Rejected reason: ** REJECT ** DO NOT USE THIS CVE RECORD. ConsultIDs: none. Reason: This record was in a CNA pool that was not assigned to any issues during 2020. Notes: none."
    }
  ]
}