{
  "cveId": "CVE-2025-53366",
  "eventName": "New CVE Received",
  "cveChangeId": "F8D26620-8696-4A71-BA21-58161360EDF6",
  "sourceIdentifier": "security-advisories@github.com",
  "created": "2025-07-04T22:15:22.300",
  "details": [
    {
      "action": "Added",
      "type": "Description",
      "newValue": "The MCP Python SDK, called `mcp` on PyPI, is a Python implementation of the Model Context Protocol (MCP). Prior to version 1.9.4, a validation error in the MCP SDK can cause an unhandled exception when processing malformed requests, resulting in service unavailability (500 errors) until manually restarted. Impact may vary depending on the deployment conditions, and presence of infrastructure-level resilience measures. Version 1.9.4 contains a patch for the issue."
    },
    {
      "action": "Added",
      "type": "CVSS V4.0",
      "newValue": "AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X"
    },
    {
      "action": "Added",
      "type": "CWE",
      "newValue": "CWE-248"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/modelcontextprotocol/python-sdk/commit/29c69e6a47d0104d0afcea6ac35e7ab02fde809a"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/modelcontextprotocol/python-sdk/pull/822"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/modelcontextprotocol/python-sdk/security/advisories/GHSA-3qhf-m339-9g5v"
    }
  ]
}